channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=24.2
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - matplotlib==3.10.0
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
